### ISSUE TITLE
질문 이곳에다 하는 게 맞나요?

### ISSUE THREAD

**Issue by ahwlsdn123** [snu-sf-class/swpp202001#1]
2017-13937 모진우 학생

**Comment by ahwlsdn123** [comment]
그리고 이곳에 질문을 올리면 다른 학생들과 공유가 되나요??

**Comment by ahwlsdn123** [comment]
make를 입력하면 아래와 같은 메시지가 뜹니다. 어떤 식으로 해결해야 할까요??

Command 'make' not found, but can be installed with:

sudo apt install make
sudo apt install make-guile

**Comment by aqjune** [comment]
안녕하세요, 질문은 swpp@sf.snu.ac.kr 를 이용 바랍니다.
`sudo apt install make`를 입력하셔서 make를 설치하시면 됩니다.
