### ISSUE TITLE
README 오타

### ISSUE THREAD

**Issue by elzino** [snu-sf-class/swpp202001#10]
안녕하세요 컴퓨터공학부 이진호입니다.

Apr. 24: Assignment 5 is announced. Deadline is May. 5 (11:59 pm). You can use issue 7 and issue 8 to ask questions.

큰 문제는 아니지만 README.md 마지막  문장에 Issue 7 and issue 8이 Issue 8 and issue 9로 바뀌어야 할 거 같습니다.

**Comment by aqjune** [comment]
지적 감사합니다. :)
